#define SERIAL_BAUD 115200
#define SLEEP_DURATION 3e8
#define BMP_SENSOR_I2C_ADDRESS 0x76
#define SHT_SENSOR_I2C_ADDRESS 0x44
#define RELAY_PIN 12
#define MUX_PIN_S0 D3
#define MUX_PIN_S1 D4
#define MUX_PIN_S2 D7
#define MUX_PIN_S3 D8
#define WIFI_SSID ""
#define WIFI_PASSWORD ""
#define MQTT_HOST ""
#define MQTT_PORT 1883
#define MQTT_USER ""
#define MQTT_PASSWORD ""
#define MQTT_CLIENT_ID "Solar_Weather_Station"
#define MQTT_TOPIC "solar-weather-station/sensors"
#define MQTT_KEEP_ALIVE_TOPIC "solar-weather-station/keep-alive"