export enum SensorType {
  Temperature = 'Temperature',
  Humidity = 'Humidity',
  InternalTemperature = 'Internal Temperature',
  InternalHumidity = 'Internal Humidity',
  Pressure = 'Pressure',
  Illuminance = 'Illuminance',
  BatteryVoltage = 'Battery Voltage',
  BatteryCurrent = 'Battery Current',
  BatteryPower = 'Battery Power',
  SolarPanelVoltage = 'Solar Panel Voltage',
  SolarPanelCurrent = 'Solar Panel Current',
  SolarPanelPower = 'Solar Panel Power',
  BatteryLevel = 'Battery Level',
}
