; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1-n16r8v]
platform = espressif32
board = esp32-s3-devkitc-1-n16r8v
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
build_flags =
	-D ELEGANTOTA_USE_ASYNC_WEBSERVER=1
	-D MQTT_MAX_PACKET_SIZE=512
lib_ignore =
	RPAsyncTCP
	ESPAsyncTCP
lib_deps =
	bblanchon/ArduinoJson@^7.2.2
	esp32async/ESPAsyncWebServer@^3.11.0
	ayushsharma82/ElegantOTA@^3.1.7
	knolleary/PubSubClient@^2.8
	adafruit/Adafruit BME280 Library@^2.3.0
	sensirion/arduino-sht@^1.2.6
	wollewald/BH1750_WE@^1.1.10
	robtillaart/INA226@^0.6.6
