export enum WeatherMeasurementType {
    Temperature = 'temperature',
    Humidity = 'humidity',
    Pressure = 'pressure',
    InternalTemperature = 'internalTemperature',
    InternalHumidity = 'internalHumidity',
    Illuminance = 'illuminance',
    BatteryVoltage = 'batteryVoltage',
    BatteryCurrent = 'batteryCurrent',
    BatteryPower = 'batteryPower',
    BatteryLevel = 'batteryLevel',
    SolarPanelVoltage = 'solarPanelVoltage',
    SolarPanelCurrent = 'solarPanelCurrent',
    SolarPanelPower = 'solarPanelPower',
}
