name: Build and deploy
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
jobs:
  build:
    runs-on: self-hosted
    environment: development
    steps:
      - uses: actions/checkout@v3
      - run: |
          docker stop $(docker ps -q --filter ancestor=${{ secrets.CONTAINER_NAME }}:${{ secrets.CONTAINER_TAG }}) || true && docker rm --force ${{ secrets.CONTAINER_NAME }} || true && docker rmi --force ${{ secrets.CONTAINER_IMAGE }}:${{ secrets.CONTAINER_TAG }} || true
          docker build . -t ${{ secrets.CONTAINER_IMAGE }}:${{ secrets.CONTAINER_TAG }}
          docker run -p 3000:3000 --name ${{ secrets.CONTAINER_NAME }} -d ${{ secrets.CONTAINER_IMAGE }}:${{ secrets.CONTAINER_TAG }}